/* AUTO-GENERATED by decode_icons.mjs — built-in LVGL template icons.
 * Each: { symbol (C name), file, w, h, cf, dataUrl (PNG preview) }.
 * 42 icons from twi_LVGL_templates/. Do not edit by hand. */
export const TEMPLATE_ICONS = [
  {
    "symbol": "arrow_next",
    "file": "arrow_next.c",
    "w": 12,
    "h": 19,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAATCAYAAACk9eypAAAAXUlEQVR4nGNgllFnAmGV1kOXYWx8mAGmGIYJakBWTIwmDBsIaWJA9gMxmhiQOcRoYkAXIKQJQwMhTVg14NOEUwMuTdSxgSQ/kBRKJMUDSTFNUlqiOLUSlYGYSchxAK1q4uMjhY9uAAAAAElFTkSuQmCC"
  },
  {
    "symbol": "arrow_prev",
    "file": "arrow_prev.c",
    "w": 12,
    "h": 19,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAATCAYAAACk9eypAAAAWUlEQVR4nGNgllFnIoQlWg9dhrEZiFGMjPFqQFeMVwM2xTidhEsxVg34FGNoIKQYRQMxiuEaiFUM1kCKYvJsIMsPZIUSWfFAVkyTlZbISq3YNBGVgZA1gdgAHE/i00FiPv4AAAAASUVORK5CYII="
  },
  {
    "symbol": "arrow_symbol",
    "file": "arrow_symbol_up.c",
    "w": 13,
    "h": 10,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAKCAYAAABv7tTEAAAAP0lEQVR4nJXLsQ0AIAwDQc/BtIzGZkZEIFEksVx89weScLNBi8ZctNABAFjBErwy2IIKSpDBmBX44X31nOSjDbuuFpxTpfhVAAAAAElFTkSuQmCC"
  },
  {
    "symbol": "arrow_symbol_left",
    "file": "arrow_symbol_left.c",
    "w": 10,
    "h": 13,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAANCAYAAACQN/8FAAAAO0lEQVR4nGP4//8/Ay4s1XDgPwMDAwRTrBBFES6FGIqwKcSqCF0hTkXICvEqIstEktxIkq9JCkeKohAAYlkWnJYGXpYAAAAASUVORK5CYII="
  },
  {
    "symbol": "arrow_symbol_right",
    "file": "arrow_symbol_right.c",
    "w": 10,
    "h": 13,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAANCAYAAACQN/8FAAAAPUlEQVR4nGNgYGD4D8JSDQf+////nwEXZiBZISHFKArxKcZQiEsxVoXYFONUiK6YMhOJciNRviYqHKkWhQC76hac/dOISwAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "back_icon_image",
    "file": "back_icon_image.c",
    "w": 12,
    "h": 19,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAATCAYAAACk9eypAAAAVUlEQVR4nGPQ1NRkIISlGg78h7GJUgzDBDUgK4ZhkhTjtAGXYqwa8CnG0EBIMYoGYhTDNRCrGKyBFMXk2UCWH8gKJbLigayYJistkZVaycoPyJpgbAB0oAiWoLKhbwAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "backup_icon_released",
    "file": "backup_icon_released.c",
    "w": 20,
    "h": 20,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAXklEQVR4nGPQ1NRk+I8DgOSQ5dH52NTjlCTHQBCgrYEwDeiYWPlRA2loILl8rAb+RwPoBuCTJ+hCQoCkMCTWMJIihRjDSI5lQoYNjnRICNPPQGoA6htISkImBEBmAQB5fxdhCqWdZgAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "ble_connected_small",
    "file": "ble_connected_small.c",
    "w": 18,
    "h": 15,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAAPCAYAAADphp8SAAAAZUlEQVR4nGNgwAH+QwEueaI1/UcCFBkGY1NsGLqhZBuGy6vIYlINB/6DMIoAPk3ofGT1KIZhmIzmMnRD0NViGISsAJ8hBA2iiouoEka4XILPcKIMYaAkHVElZePzCskpmhjD8QEATqM/KWZ5xf4AAAAASUVORK5CYII="
  },
  {
    "symbol": "ble_off_image",
    "file": "ble_off_image.c",
    "w": 28,
    "h": 28,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAYAAAByDd+UAAAAoElEQVR4nL3UDQqAIAwFYC/o/Y+zMAjGYz/O9nwQlJCfremYc8q6RiGiUnnvzQdWUIHQUQTpqEauoAjQUWtyKupNTEMpYIS2lzRDW5umglKwDKVgGUrBIpSa9UXXUP3P6KgYoaHYjfq+HbVaH5/bUG+fWWO/0WhTe+PHaHaCRAspozvHVVTmMrpzNnpNRGkkBKOKULo3q0gLuou1oRUM0QcGlIHjotQZ2QAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "ble_off_small",
    "file": "ble_off_small.c",
    "w": 18,
    "h": 15,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAAPCAYAAADphp8SAAAAYklEQVR4nK3TUQrAMAgD0FzQ+x/HMVhBQpSpDfSn0IdCCgAwM38PKP6F78sozENW2AHWWHy8wvjhtTXbiJpsjJwpsmq0oTXG64ywrIgtLAKqR78wniJrdompVaq/Nl5TJWIPV7HkSTYFMPcAAAAASUVORK5CYII="
  },
  {
    "symbol": "ble_on_image",
    "file": "ble_on_image.c",
    "w": 28,
    "h": 28,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAYAAAByDd+UAAAAiUlEQVR4nM3TSw7AIAgEUO9/6XZrCJ8RZoysWu3wEqVrNerbqpMfgVdQC8rRHRmjSNh+M0KRsLcvRaM9GSoBswb0I60aUYcGQb1nGuahXlGxCpVgESrFroNP3J98Qpf6t/AaRu9jNGqUrbXRrEG1foxWQSqIhKhHioRkQ4OAcswicswDpZgFT7M/L4zNTwJw8wIAAAAASUVORK5CYII="
  },
  {
    "symbol": "ble_on_small",
    "file": "ble_on_small.c",
    "w": 18,
    "h": 15,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAAPCAYAAADphp8SAAAASUlEQVR4nGNgwAP+QwE+NURp+o8EKDIMxqbYMHRDyTYMl1fJdhnZhmBzGdmGoBtEtiFUcxFVwogqsUaVdESVlI3PK1SLNWLUAgAO8PsFlpoxbQAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "brightness_icon",
    "file": "brightness_icon.c",
    "w": 22,
    "h": 22,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAAZUlEQVR4nNXQUQ4AEAwDUPe/qFss4kOCMO1GIPEj7WNCAJeIxLzRPLzehK3lZa8EGBzu9IG6OEOoKWegdsE9GEVpfAs8Cljh5uwY/N8fe3EKRXEaQ3Cto77QMtUyhKLenr/8BZwAlGiTia5jQyQAAAAASUVORK5CYII="
  },
  {
    "symbol": "confirm_icon_image",
    "file": "confirm_icon_image.c",
    "w": 30,
    "h": 30,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAAsklEQVR4nM3XPQqAMAwG0J7N0cHJ07p4I50FQalQUKltvvzVQqZCXiLUpiEQVz93Y4xh6vZcpH1qPhGmXgQXFBeggd5xt07hzi3QaueW6CfugWbxJrAVum7LUcQt4IimcIPvaBH2RlOowQiqBqMoCa4l46BVuJT0vYegUMfv5BL0ginHKdedBIXOsRYKwxqf9wGj/2sJOPzidmo6CDQdfSxx8ojrPt5q4+wnjfsThlMEip1kiN5hJAavkgAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "device_info_icon",
    "file": "device_info_image.c",
    "w": 21,
    "h": 21,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAcklEQVR4nO2SQQ7AIAgEfZxP6Wv6aZt4M0GYMe2tJF5kGVi09etu2RlBVDUKRuEljDRMocZipkdAm0MT2vxyaW1Gmgm1eySNyylPwAhK3fzQFfrWl5rQT/4pKbJ5VGhzRw9S6VMhsRtp0BS72NUqi3Q1D7nZugpiMSWVAAAAAElFTkSuQmCC"
  },
  {
    "symbol": "empty_battery_charge_image",
    "file": "empty_battery_charge_image.c",
    "w": 19,
    "h": 9,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAJCAYAAADQHRcxAAAAOklEQVR4nGNgYGBgyMkv/E8uZkAGxComykCSbMahnmzD8BpKSBMhgNUwclyC02XkhBXZYUa15EGsQQCligxXT1XBGwAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "empty_battery_image",
    "file": "empty_battery_image.c",
    "w": 19,
    "h": 9,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAJCAYAAADQHRcxAAAAL0lEQVR4nGNgYGBgyMkv/E8uZkAGlBiEYSDNDIMBZDY+gGEozQyj2LuDNwKomc4AUQKIr6wp6N4AAAAASUVORK5CYII="
  },
  {
    "symbol": "estr_power_off_released",
    "file": "power_off_released.c",
    "w": 21,
    "h": 21,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAb0lEQVR4nO2TOw7AMAhDcx3f/4Dt2qgBPydLhyKxBPPEJwxJw/n1MKK3gm9Cq8QOunqPEmkMtZfG27aTmU7QJIFqbJXJ9n8oh1J/QU/B0/bJP02goheVVCl6++kSt7bs9K2wgjsNqqKyKjdqkY7mBlnIooZ+yy6iAAAAAElFTkSuQmCC"
  },
  {
    "symbol": "full_battery_charge_image",
    "file": "full_battery_charge_image.c",
    "w": 19,
    "h": 9,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAJCAYAAADQHRcxAAAAO0lEQVR4nGNgYGBg+E8BYEAGxComykCSbMahnmzD8BpKSBMhgNUwclyC02WEDCUqKAjaRophxHqBGIMAC5fSPE/KYr0AAAAASUVORK5CYII="
  },
  {
    "symbol": "full_battery_image",
    "file": "full_battery_image.c",
    "w": 19,
    "h": 9,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAJCAYAAADQHRcxAAAAJUlEQVR4nGNgYGBg+E8BYEAGlBiEYeCgMwxu6PA2jDYRQM10BgA0vWmzyEgQHAAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "half_battery_charge_image",
    "file": "half_battery_charge_image.c",
    "w": 19,
    "h": 9,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAJCAYAAADQHRcxAAAAPklEQVR4nGNgYGBg+E8A5OQX4sQMyICQQTB1RBlIrGH4DCXbMLyGEtJECGA1jByX4HQZOWFFdphRLXkQaxAAJENx05wUP2gAAAAASUVORK5CYII="
  },
  {
    "symbol": "half_battery_image",
    "file": "half_battery_image.c",
    "w": 19,
    "h": 9,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAJCAYAAADQHRcxAAAALElEQVR4nGNgYGBg+E8A5OQX4sQMyICQQYQMQzFw0BkGN3R4G0abCKBmOgMAjvjpGLr2V6gAAAAASUVORK5CYII="
  },
  {
    "symbol": "help_symbol",
    "file": "help_symbol.c",
    "w": 8,
    "h": 15,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAPCAYAAADZCo4zAAAAM0lEQVR4nGNgYGBg+Pfv3xxsmAGfJFwRug6spqADyhTgtYJ8ScodhqwAqyRBQJIDSXYDAGRdzGcxTMNlAAAAAElFTkSuQmCC"
  },
  {
    "symbol": "installed_apps_icon_released",
    "file": "installed_apps_icon_released.c",
    "w": 17,
    "h": 20,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAAAUCAYAAABroNZJAAAAPUlEQVR4nGPQ1NRkwIX/IwF86nBKjBoyasjQMOQ/EYAol5BiAF7vEGsAfQIWZhAhNQQNIQYTFRuEwOAxBABOgSFoTkT7vwAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "menu_dots",
    "file": "menu_dots.c",
    "w": 18,
    "h": 3,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAADCAYAAACeRF9pAAAAF0lEQVR4nGP4jwQY0MB/NIBPnmHQGQQAJIR3iVt44FQAAAAASUVORK5CYII="
  },
  {
    "symbol": "menue_icon_image",
    "file": "menue_icon_image.c",
    "w": 24,
    "h": 15,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAPCAYAAAD+pA/bAAAAKUlEQVR4nGOQajjwn5aYYehboKmpSVM8DCwY+pE8mooG3oKhH8m0tgAA9+tAZ4nnaVUAAAAASUVORK5CYII="
  },
  {
    "symbol": "next_icon_image",
    "file": "next_icon_image.c",
    "w": 12,
    "h": 19,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAATCAYAAACk9eypAAAAWklEQVR4nGPQ1NRkAGGphgP/YWx8GK4YhglqQFZMjCYMGwhpgjOI1YTCIUYThgmENGF1Jz5NOEMDlya8YY5NE3VsIMkPJIUSSfFAUkyTlJYoTq1EZSBNEnIcABx1CJagZK4YAAAAAElFTkSuQmCC"
  },
  {
    "symbol": "open_settings_pressed",
    "file": "open_settings_pressed.c",
    "w": 22,
    "h": 20,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAUCAYAAACJfM0wAAAAbklEQVR4nGPQ1NRkwIelGg78x4YJ6cMrSTWDsWkg1mB0MawGkGowNnGcmvEZSkgN2GBCmsnFeL2LzYvEqiU79gmpJ6iYFIPxpmNS0io+tfQxmCZBQZPIo0lyo3sGoThL07QQommxSW7s48I0MxgAUjKML2ggI20AAAAASUVORK5CYII="
  },
  {
    "symbol": "open_settings_released",
    "file": "open_settings_released.c",
    "w": 22,
    "h": 20,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAUCAYAAACJfM0wAAAAbUlEQVR4nL2UwQ0AIAgDXYf9B9TEJ4EWUDDhg+1FRVgislBsZzEf3PwGtgxRsM6ZgCzYyrtmBGWaC2bm6oLX1afIaMvVZ3oqzoDhP45AI9oZcMtTsGKUiueJLENUO98gzy3dOoRax2a1+l60gQ/bhA6RLaEy4QAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "quadrate_battery_charge_image",
    "file": "quadrate_battery_charge_image.c",
    "w": 19,
    "h": 9,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAJCAYAAADQHRcxAAAARUlEQVR4nGNgYGBg+I8GcvILicYMyADdIHTDYOqIMpBYw/AZSrZheA2FGYBLEyGA1TBChhIVGbi8SYphJIcZ2cmD3HQGANXOTk7JFJvLAAAAAElFTkSuQmCC"
  },
  {
    "symbol": "quadrate_battery_image",
    "file": "quadrate_battery_image.c",
    "w": 19,
    "h": 9,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAJCAYAAADQHRcxAAAALElEQVR4nGNgYGBg+I8GcvILicYMyADdIFINQzFw0BkGN3R4G0abCKBmOgMAn1WsNAtFpV4AAAAASUVORK5CYII="
  },
  {
    "symbol": "reject_icon_image",
    "file": "reject_icon_image.c",
    "w": 30,
    "h": 30,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAAtklEQVR4nOXXXwqAIAwHYF87j16no0tX8ABCUSCETP1N5x/qYU/Fvk3DptqUUkgcWu93WGM8FeE5mq8JaylCFOQUkIRb0TdehKU6RTrv1mmp8yEohQ9DY3wejKDeuTME8h6Cs2Eqcem5GBwnr4LRvaHwUkG5gGEE5+RiwTmcm4cNI3v+naUW/bjQUysF1ODrHyAWOA45S/3A//s7TR0Epo4+PXFq0lxjvJXGc7eJta4wNUVwL20X7HkE9CfPNEAAAAAASUVORK5CYII="
  },
  {
    "symbol": "settings_menu_back",
    "file": "twi_template_settings_menu1.c",
    "w": 19,
    "h": 12,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAMCAYAAACA0IaCAAAAXUlEQVR4nGPQNXP6TwhLNRwgqAaEGYgxCIYpMgzZIGIMxGkYNoMIGYjVMHwG4TMQwzBcGokxkIEYg4iVZyBWITHqGMiJNVzqGUg1CJ+BGC4jxiBcCRolzEgxCJs+AEzHsM+KJdCpAAAAAElFTkSuQmCC"
  },
  {
    "symbol": "settings_menu_back",
    "file": "twi_template_settings_menu3.c",
    "w": 19,
    "h": 12,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAMCAYAAACA0IaCAAAAXUlEQVR4nGPQNXP6TwhLNRwgqAaEGYgxCIYpMgzZIGIMxGkYNoMIGYjVMHwG4TMQwzBcGokxkIEYg4iVZyBWITHqGMiJNVzqGUg1CJ+BGC4jxiBcCRolzEgxCJs+AEzHsM+KJdCpAAAAAElFTkSuQmCC"
  },
  {
    "symbol": "small_cross_image",
    "file": "small_cross_image.c",
    "w": 13,
    "h": 13,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAAQUlEQVR4nGO4a2z8H4YZ8AAUdcgcXBox1KALoGvEKY9LgpCBWBUQ43S8GvEFEmEnUWwTyX4iOfTIiieKUwSxgQQABzDtE/7lUYYAAAAASUVORK5CYII="
  },
  {
    "symbol": "supported_coins_icon",
    "file": "supported_coins_icon.c",
    "w": 24,
    "h": 22,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAWCAYAAADafVyIAAAAbUlEQVR4nNVSRwoAIAzr/x/od+pVwZGhggWPGSaJaC4zC/qCOYaYFlHJYZH/Ba53oAhJpLQbx7WCmeLZWOQYEYA0gpGa677DotnLUz6d/TSmqwLIZO2IlsM/3cHTkp2YKHeWABIF+4tdp9tDiSsUpjMgqeiZPgAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "three_quadrate_battery_charge_image",
    "file": "three_quadrate_battery_charge_image.c",
    "w": 19,
    "h": 9,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAJCAYAAADQHRcxAAAASUlEQVR4nGNgYGBg+E8iyMkvhGMGZEBIIzZ1yIahGEisYcjqqWYYDKAbCDaUkCZCAKthhAzFF2Y4DcMXVlSLAKIMI8ZAdIDLIAC08ZVYv4+VFQAAAABJRU5ErkJggg=="
  },
  {
    "symbol": "three_quadrate_battery_image",
    "file": "three_quadrate_battery_image.c",
    "w": 19,
    "h": 9,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAAJCAYAAADQHRcxAAAALElEQVR4nGNgYGBg+E8iyMkvhGMGZECqQeiGoRg46AyDGzq8DaNNBFAznQEAsB8mCykjDawAAAAASUVORK5CYII="
  },
  {
    "symbol": "update_icon",
    "file": "update_icon.c",
    "w": 21,
    "h": 29,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAdCAYAAABFRCf7AAAAY0lEQVR4nO3SwQ4AEAwD0P3/T9dVsKy2Li56JF6Jmb0KAMhBKYopcnBNC1oqaIejwhTMvIY+xJZucPVXW9Cj8dGPamY1XqyGuW2qFEu8/TLs5Rpm8RQc4WnUK5CA1jl2UvAmA/zgAhv0zCTbAAAAAElFTkSuQmCC"
  },
  {
    "symbol": "usb_mode_icon",
    "file": "usb_mode_icon.c",
    "w": 33,
    "h": 21,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAVCAYAAADID4fUAAAAcUlEQVR4nOXUSw4AIQgDUO9/aY17qXyKkNjtRHjRZsYgZB7CmBsCpCOkpX8hpEVlCMs31xIrgBLNu0YR8LymXIxbgJ1BiBdpgdgpR6g7YSqZpxMI4h5IgtOHUpefEPPyC08BIEg5AiUNYYGkIrSo9ogFFAsENd5MocAAAAAASUVORK5CYII="
  },
  {
    "symbol": "usb_off_image",
    "file": "usb_off_image.c",
    "w": 28,
    "h": 20,
    "cf": "LV_IMG_CF_INDEXED_2BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAUCAYAAACeXl35AAAAeElEQVR4nO3UUQrAIAwD0F6w9z9O/dnAoU1ikYFjAX861yfd0KyLu8e97K386JloXFHRmAQ9G3ojUEUZ+OifgX1NHS86gASuoltBBc1A2hjVEUq/XwVEaP7LFEfK0Nk720CESiAbRVZfvRwgyvaoKJpSOd+68I9BGwh2SC985d6sAAAAAElFTkSuQmCC"
  },
  {
    "symbol": "usb_on_image",
    "file": "usb_on_image.c",
    "w": 28,
    "h": 20,
    "cf": "LV_IMG_CF_INDEXED_1BIT",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAUCAYAAACeXl35AAAAXUlEQVR4nO2QQQoAIAgE/f+n7dKhyNVVIgicY247qEjTVNAJel9nCmDnKSEqY4Rbf0XIXutfYfTHyqeFjNSaH90ZISqOhOUNo4y3dVj8ROid4lbGDTIZRogu1PzHACXSvV+hfu4vAAAAAElFTkSuQmCC"
  }
]
